#!/bin/bash

# make this pc to a (the) teachers pc

if [ "$USER" != "root" ]; then
   echo "you must be root to do this"
   exit 1
fi

VLCOMMON=/usr/share/vlizedlab/scripts/common
if [ -f $VLCOMMON ]; then source $VLCOMMON ; else exit 1; fi

echo "This will upgrade this PC to a teachers PC"
echo "Dont forget to edit /etc/vlizedlab/mystudentlist first!"
echo "You will have to type the root password for each machine in the room"
echo "press <ctrl>-c to stop, <enter> to proceed"
read IN
sleep 1

if [ ! -f /root/.ssh/id_rsa -o ! -f /root/.ssh/id_rsa.pub ]; then
   ssh-keygen -t rsa -P "" -f /root/.ssh/id_rsa
fi

IPLIST="`$VLSCRIPTDIR/chooseips`"


for ip in $IPLIST ; do

   echo "registering root login for $ip:"
   cat /root/.ssh/id_rsa.pub | ssh root@$ip 'cat >> /root/.ssh/authorized_keys'

done


