#!/bin/bash

echo "Update Virtual Machines"

VLCOMMON=/usr/share/vlizedlab/scripts/common
if [ -f $VLCOMMON ]; then source $VLCOMMON ; else exit 1; fi

TMPLIST=/tmp/vmlist$$


_updatevm () { # $1 is "METHOD,HNAME,URL,TYP/MNAME: FILES"
    METHOD="`echo $1 | awk -F, '{print $1}'`"
    URL="`echo $1 | awk -F, '{print $3}'`"
    TYP="`echo $1 |    awk -F, '{print $4}' | awk -F/ '{print $1}'`"
    MNAME="`echo $1 |  awk -F, '{print $4}' | awk -F/ '{print $2}' | awk -F: '{print $1}' `"
    FILELISTRAW="`echo $1 |  awk -F, '{print $4}' | awk -F/ '{print $2}' | awk -F: '{print $2}'`"
#    FILELIST="`echo "$FILELISTRAW" | sed '1,$ s/%[-a-zA-Z0-9_\.@]*//g'`"
#    FILTERSTRING="`echo "$FILELISTRAW" | sed '1,$ s/[ \t][ \t]*/|/g' | sed '1,$ s/^|//' | sed '1,$ s/|$//' | sed '1,$ s/%//g'`"
    FILELIST="`echo "$FILELISTRAW" | sed '1,$ s/[-a-zA-Z0-9_\.]*_local[-a-zA-Z0-9_\.@]*//g'`"
    FILTERSTRING="`echo "$FILELISTRAW" | sed '1,$ s/[ \t][ \t]*/|/g' | sed '1,$ s/^|//' | sed '1,$ s/|$//'`|[-a-zA-Z0-9_\.]*_local[-a-zA-Z0-9_\.@]*"


    if [ "$TYP" = vb ]; then
       for file in $FILELIST ; do
          if [ $METHOD = http ]; then
              mkdir -p $VBHOME/$MNAME
              wget $WGETOPTS -O $VBHOME/$MNAME/$file "$URL/$MNAME/$file"
              if [ $? != 0 ]; then
                echo "ERROR downloading $URL/$MNAME/$file"
                if [ -f $VBHOME/$MNAME/$file ]; then rm -f $VBHOME/$MNAME/$file; fi
              fi
          elif [ $METHOD = rsync ]; then
              mkdir -p $VBHOME/$MNAME
              rsync $RSYNCOPTS $URL/$MNAME/$file $VBHOME/$MNAME/$file
              if [ $? != 0 ]; then
                echo "ERROR downloading $URL/$MNAME/$file"
                if [ -f $VBHOME/$MNAME/$file ]; then rm -f $VBHOME/$MNAME/$file; fi
              fi
          else
            echo "ERROR: unknown method $METHOD"
          fi
       done
       for dd in `/bin/ls $VBHOME/$MNAME | egrep -v "$FILTERSTRING"` ; do
            rm -Rvf $VBHOME/$MNAME/$dd
       done
       chown -Rvf student.student $VBHOME/$MNAME
       find $VBHOME/$MNAME -name '*.sh' -exec chmod -v 755 {} \;
    else
       echo "ERROR: unknown type $TYP"
    fi

#        echo "Updating  Virtual Machines $VBOXRSYNCHOST::vbox/$1"
# -c --size-only
#        rsync -vrptlO -z --progress --delete  -f '- *~' $VBOXRSYNCHOST::vbox/$1  $VMHOME
#        chown -Rvf student.users $VMHOME/$1
#        chmod -Rvf 775 $VMHOME/$1
#        echo "Update of Virtual Machines $VBOXRSYNCHOST::vbox/$1 done."
}


_expandmachines () {
    cat $1 | awk '/^#/ {next;} /^[ \t]*$/ {next;} {print;}' | \
    while read LINE ; do
      echo "$2,$3,$4,$LINE" >> $TMPLIST  #Now format is METHOD,HNAME,URL,TYP/MNAME: FILES
    done
}

# Generate Machine list

if [ -f $TMPLIST ]; then rm $TMPLIST; fi

cat $VLSOURCELIST | grep -v '^#' | while read line ; do
   METHOD="`echo $line | awk '{print $1}'`"
   NAME="`echo $line | awk '{print $2}'`"
   URL="`echo $line | awk '{print $3}'`"
   if [ "$METHOD" = "" -o "$NAME" = "" -o "$URL" = "" ]; then
      true # invalid line
   else
       echo "Loading Machine List from $METHOD $NAME $URL"
       if [ -f $TMPLIST.tmp ]; then rm $TMPLIST.tmp; fi

       if [ $METHOD = http ]; then
           wget $WGETOPTS -O $TMPLIST.tmp $URL/machinelist
           if [ $? = 0 ]; then
              _expandmachines $TMPLIST.tmp $METHOD $NAME $URL 
           fi
       elif [ $METHOD = rsync ]; then
           rsync $RSYNCOPTS  $URL/machinelist $TMPLIST.tmp
           if [ $? = 0 ]; then
              _expandmachines $TMPLIST.tmp $METHOD $NAME $URL 
           fi
       else 
         echo "ERROR: Unknown download method $METHOD"
       fi
   fi

done


MENU=$TMPLIST.menu
echo -n "0 _A_L_L_ " > $MENU

NR=1
cat $TMPLIST | while read line ; do
   HNAME="`echo $line | awk -F, '{print $2}'`"
   TNAME="`echo $line | awk -F, '{print $4}' | awk -F: '{print $1}'`"
#   MENU="$MENU $NR $HNAME:$TNAME"
   echo -n "$NR $HNAME:$TNAME " >> $MENU
   NR=`expr $NR + 1`
done

MM="`cat $MENU`"

choice=`dialog --cr-wrap --backtitle "$VLTITLE" \
               --menu 'Which Virtual Machine do you want to load/update?' 0 0 0 $MM 3>&1 1>&2 2>&3`

clear

#echo "Updating Virtual Machine $choice"

case $choice in 
   0)
     echo "Updating All Virtual Machines"
     cat $TMPLIST | while read line ; do
          _updatevm "$line"
     done
     echo "waiting..."
     sleep 1
     ;;
   [0-9]*)
     NR=1
     cat $TMPLIST | while read line ; do
         if [ $NR = $choice ]; then
            _updatevm "$line"
         fi
         NR=`expr $NR + 1`
     done
     echo "waiting..."
     sleep 1
     ;;
esac


