#!/bin/bash

sleep 1

# if [ -x /etc/installonfirstboot.sh ]; then
# 	/etc/installonfirstboot.sh
# fi

# SCRIPT=/usr/share/vlizedlab/scripts/startmenu
#SCRIPT=/usr/share/vlizedlab/scripts/startmenumaint

#if [ -x $SCRIPT ]; then
#    $SCRIPT
#else
#    login
#fi

login
